/* -------------------------------------------------------------------------- */
/* ----- This file is automatically generated by Flutter Butler ----- */
/* ---- Do not modify this file manually. Any changes may be overwritten. --- */
/* ------------------------ Published by: nahidhasannoyon ------------------------ */
/* -------------------------------------------------------------------------- */

// cSpell:disable
class AppFonts {
  // Inter Font Family
  static const inter = 'Inter';

  // Poppins Font Family
  static const poppins = 'Poppins';
}
// cSpell:enable