/* -------------------------------------------------------------------------- */
/* ----- This file is automatically generated by Flutter Butler ----- */
/* ---- Do not modify this file manually. Any changes may be overwritten. --- */
/* ------------------------ Published by: BrotherDev ------------------------ */
/* -------------------------------------------------------------------------- */

import 'package:flutter/material.dart';
// cSpell:disable
class AppFonts {

  // Inter_18pt Font Family
  static const TextStyle inter18ptBlack = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptBlackItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptBold = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptBoldItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptExtraBold = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptExtraBoldItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptExtraLight = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptExtraLightItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptLight = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptLightItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptMedium = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptMediumItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptRegular = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptSemiBold = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptSemiBoldItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptThin = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.normal,
  );

  // Inter_18pt Font Family
  static const TextStyle inter18ptThinItalic = TextStyle(
    fontFamily: 'Inter_18pt',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptBlack = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptBlackItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptBold = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptBoldItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptExtraBold = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptExtraBoldItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptExtraLight = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptExtraLightItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptLight = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptLightItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptMedium = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptMediumItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptRegular = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptSemiBold = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptSemiBoldItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptThin = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.normal,
  );

  // Inter_24pt Font Family
  static const TextStyle inter24ptThinItalic = TextStyle(
    fontFamily: 'Inter_24pt',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptBlack = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptBlackItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptBold = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptBoldItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptExtraBold = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptExtraBoldItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptExtraLight = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptExtraLightItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptLight = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptLightItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptMedium = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptMediumItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptRegular = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptSemiBold = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptSemiBoldItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptThin = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.normal,
  );

  // Inter_28pt Font Family
  static const TextStyle inter28ptThinItalic = TextStyle(
    fontFamily: 'Inter_28pt',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsBlack = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsBlackItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsBold = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsBoldItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsExtraBold = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsExtraBoldItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w800,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsExtraLight = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsExtraLightItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsLight = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsLightItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w300,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsMedium = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsMediumItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w500,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsRegular = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsSemiBold = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsSemiBoldItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
  );

  // Poppins Font Family
  static const TextStyle poppinsThin = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.normal,
  );

  // Poppins Font Family
  static const TextStyle poppinsThinItalic = TextStyle(
    fontFamily: 'Poppins',
    fontWeight: FontWeight.w100,
    fontStyle: FontStyle.italic,
  );
}