/* -------------------------------------------------------------------------- */
/* ----- This file is automatically generated by Flutter Butler ----- */
/* ---- Do not modify this file manually. Any changes may be overwritten. --- */
/* ------------------------ Published by: BrotherDev ------------------------ */
/* -------------------------------------------------------------------------- */
// cSpell:disable

class AppImages {
  static const String appLogo = "assets/images/app_logo.png";
  static const String appleLogo = "assets/images/apple_logo.png";
  static const String bdFlag = "assets/images/bd_flag.png";
  static const String fbLogo = "assets/images/fb_logo.png";
  static const String googleLogo = "assets/images/google_logo.png";
  static const String leafs = "assets/images/leafs.png";
  static const String msLogo = "assets/images/ms_logo.png";
  static const String office = "assets/images/office.png";
  static const String userPic = "assets/images/user_pic.png";
}
