/* -------------------------------------------------------------------------- */
/* ----- This file is automatically generated by Flutter Butler ----- */
/* ---- Do not modify this file manually. Any changes may be overwritten. --- */
/* ------------------------ Published by: BrotherDev ------------------------ */
/* -------------------------------------------------------------------------- */
// cSpell:disable

class AppImages {
  static const String appLogo = "assets/images/app_logo.png";
  static const String appleLogo = "assets/images/apple_logo.png";
  static const String bdFlag = "assets/images/bd_flag.png";
  static const String fbLogo = "assets/images/fb_logo.png";
  static const String googleLogo = "assets/images/google_logo.png";
  static const String leafs = "assets/images/leafs.png";
  static const String msLogo = "assets/images/ms_logo.png";
  static const String office = "assets/images/office.png";
  static const String userPic = "assets/images/user_pic.png";
  static const String homeIcon = "assets/images/home_icon.png";
  static const String person1 = "assets/images/person_1.png";
  static const String person2 = "assets/images/person_2.png";
  static const String person3 = "assets/images/person_3.png";
  static const String person4 = "assets/images/person_4.png";
  static const String person5 = "assets/images/person_5.png";
  static const String person6 = "assets/images/person_6.png";
  static const String person7 = "assets/images/person_7.png";
  static const String person8 = "assets/images/person_8.png";
}
